{
    'name': 'OGI Transit - Core Logistics',
    'version': '18.0.1.0.0',
    'category': 'Logistics',
    'author': 'Hasibul Islam',
    'website': 'https://hasibulislam.odoo.com',
    'summary': 'Core operations for OGI Transit: Lots, B/L, Containers',
    'depends': ['base', 'mail', 'contacts', 'crm', 'account'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/finance_data.xml',
        'wizard/reason_wizard_views.xml',
        'wizard/payment_wizard_views.xml',
        'wizard/assign_forwarder_wizard_views.xml',
        'wizard/pl_import_wizard_views.xml',
        'wizard/reminder_wizard_views.xml',
        'report/delivery_note_report.xml',
        'report/ogi_reports.xml',
        'views/res_partner_views.xml',
        'views/menu_views.xml',          
        'views/dashboard_views.xml',
        'views/logistics_views.xml',
        'views/finance_views.xml',
        'views/invoice_views.xml',
        'views/vendor_bill_views.xml',
        'views/res_users_views.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}